ling_flood.py
Now has a priority list over the build unit functions. 
Each build unit function returns if it wants to build the unit. 
It doesn't build the most prioritized unit if it can or waits each step so we can prioritize supply, then workers, then lings and then ultra.
=> Improved unit production

ling_flood.py
Improved several if statements and added optimal worker count calculation
=> Improvements

ling_flood.py, sc2/bot_ai.py, sc2/units.py, worker.py
=> Possible worker defense bug fix

army.py
make the use of variables clear
=> Rename enemy_build for clarity

worker.py
=> Distribute worker refactor

buildings.py, ling_flood.py
Split build spores and build spines, update comments from both, and remove unusufell code(for now we dont use the first overlord scouting info)
=> Refactoring, update comments

buildings.py, ling_flood.py, production.py, run.py
Check if there is something wrong
=> Mutalisk implementation

actions/army_control.py, actions/build/evochamber.py, actions/build/pit.py, actions/build/spire.py, actions/train/mutalisk.py, jackBot.py
reimplement missing fixes from #83
=> Fix missing retreat bug fix

actions/distribute_workers.py
this will distribute all idle workers to mineral fields
should fix #71
=> #71 fix idle workers

actions/army_control.py, actions/build/extractor.py, actions/distribute_workers.py, actions/train/zergling.py, actions/unit/drone.py, actions/unit/overlord.py, actions/upgrades/burrow.py, jackBot.py, run.py
Upgrade burrow, it's not really used anywhere yet, but it's researched
=> Include burrow - ov initial scout - improving gas mining - fix scouting bug

actions/defend_rush_buildings.py, actions/unit/overlord.py, jackBot.py
We are super aggressive now, i think that is better than waiting and dieing later as we did before
=> first version of rush building defense

.gitignore, actions/army_control.py, actions/micro.py
attack sieged tanks and improve building attack if in range
=> attack sieged tanks and improve building attack if in range

actions/army_control.py, actions/block_expansions.py, actions/unit/overlord.py, actions/upgrades/burrow.py, jack_bot.py
Dont accept yet, ill put here for you to test
=> Burrow idea attempt

actions/army_control.py, actions/block_expansions.py, actions/build/spines.py, actions/defend_rush_buildings.py, actions/train/overlord.py, actions/unit/buildings.py, actions/unit/overlord.py
=> Beating naughty 100%(Still have annoying mistakes tho)

actions/train/zergling.py
test it and tell me what you think
=> Faster mboost

README.md, actions/army_control.py, actions/build/cavern.py, actions/build/evochamber.py, actions/build/expansion.py, actions/build/hive.py, actions/build/lair.py, actions/build/pit.py, actions/build/pool.py, actions/build/spines.py, actions/build/spores.py, actions/defend_rush_buildings.py, actions/train/worker.py, actions/train/zergling.py, actions/unit/buildings.py, actions/unit/overlord.py, actions/upgrades/burrow.py, actions/upgrades/chitinous_plating.py, jack_bot.py, run.py
=> 90%vsallladder

actions/army_control.py, actions/micro.py, run.py, sc2/client.py, sc2/game_data.py, sc2/ids/effect_id.py
merging minor fixes first please :)
=> Dodging effects

actions/army_control.py, actions/build/lair.py, actions/build/spines.py, actions/defend_rush_buildings.py, actions/unit/overlord.py, actions/upgrades/burrow.py, actions/upgrades/pneumatized_carapace.py, creep_spread.py, jack_bot.py, sc2/bot_ai.py
small change to prepare for 1 base play defenses
=> changing overlord scouting logic and pylint fixes

README.md, actions/army_control.py, actions/build/cavern.py, actions/build/hive.py, actions/build/lair.py, actions/build/pit.py, actions/build/pool.py, actions/build/spines.py, actions/build/spire.py, actions/distribute_workers.py, actions/upgrades/adrenalglands.py, actions/upgrades/burrow.py, actions/upgrades/chitinous_plating.py, actions/upgrades/metabolicboost.py, actions/upgrades/pneumatized_carapace.py, data_container.py, jack_bot.py
found the pathing bug while refactoring
I forgot to change the title on part 3 its handling_walls_and_attacking
=> Refactoring everything and pathing bug fix

actions/defend_worker_rush.py, actions/distribute_workers.py, actions/micro.py, actions/train/overseer.py, actions/unit/overseer.py, jack_bot.py, run.py
Attempt to fix for #140- good on tests(it makes the mid-game slight weaker tho due to the resources spent on overseers) Review this after the micro-banelings one, also this fix a bug with weapon cd on hydras
=> Fix vs cloaked burrow units

actions/army_control.py, actions/build/extractor.py, actions/build/pool.py, actions/building_positioning.py, actions/defend_worker_rush.py, actions/distribute_workers.py, actions/micro.py, actions/train/overseer.py, actions/train/worker.py, actions/unit/overseer.py, jack_bot.py, run.py
Adding numpy and make some tweaks/simplifications, review fix vs cloaked units first
=> Implement numpy

actions/build/pool.py, actions/unit/buildings.py, actions/unit/drone.py, actions/unit/overlord.py, actions/unit/overseer.py
This patch was more optimization and organization then it was a simplification(tho it still has it f.e on overseer.py)
The only functional change is the scout selection, since its so minor there is no need for reviewing, Ill merge.
=> Optimizations, refactoring and cleaning \unit

actions/unit/overlord.py, actions/upgrades/adrenalglands.py, actions/upgrades/burrow.py, actions/upgrades/chitinous_plating.py, actions/upgrades/evochamber.py, actions/upgrades/hydra_atk_speed.py, actions/upgrades/hydra_speed.py, actions/upgrades/metabolicboost.py, actions/upgrades/pneumatized_carapace.py, jack_bot.py
No functional changes, all changes were for organization and micro-optimization purposes
=> Work on upgrades

actions/anti_cheese/defend_proxies.py, actions/anti_cheese/defend_rush_buildings.py, actions/anti_cheese/defend_worker_rush.py, actions/build/evochamber.py, actions/build/pool.py, main.py, sc2/bot_ai.py, sc2/unit.py
Already tested, very small functional change(the threshold for build pool reduced to 145), all other changes are not functional
=> Cleaning, simplifying and optimizing \anti-cheese

actions/upgrades/adrenalglands.py, actions/upgrades/burrow.py, actions/upgrades/chitinous_plating.py, actions/upgrades/evochamber.py, actions/upgrades/hydra_atk_speed.py, actions/upgrades/hydra_speed.py, actions/upgrades/metabolicboost.py, actions/upgrades/pneumatized_carapace.py
big optimization on evochamber, before it checked for hydradens-ranged upgrades every loop, now it just adds the upgrades into the list once, it is very slightly faster mid-game(about 2% on the whole game). The other changes are just cleaning
=> clean \upgrades, optimize  evochamber.py

actions/build/cavern.py, actions/build/evochamber.py, actions/build/hydraden.py, actions/build/pit.py, actions/build/spores.py
=> Fix issue 174
